<?php
require_once 'includes/db.php';
require_once 'includes/functions.php';

if (!isLoggedIn()) {
    exit('Unauthorized');
}

$user_id = $_SESSION['user_id'];

// Get all records for the user
$stmt = $pdo->prepare("SELECT * FROM energy_consumption WHERE user_id = ? ORDER BY date_recorded DESC");
$stmt->execute([$user_id]);
$records = $stmt->fetchAll();

// Calculate total
$total_units = 0;
foreach ($records as $r) { $total_units += $r['consumption_kwh']; }

function calculateTNCostPDF($units) {
    if ($units <= 100) return 0;
    $cost = 0;
    if ($units <= 200) { $cost = ($units - 100) * 4.50; }
    elseif ($units <= 400) { $cost = (100 * 4.50) + ($units - 200) * 6.00; }
    elseif ($units <= 500) { $cost = (100 * 4.50) + (200 * 6.00) + ($units - 400) * 8.00; }
    else { $cost = (100 * 4.50) + (200 * 6.00) + (100 * 8.00) + ($units - 500) * 9.00; }
    return $cost;
}

$total_cost = calculateTNCostPDF($total_units);

// Simple HTML to PDF using browser print or a basic layout
// Note: In a real production environment, you would use libraries like Dompdf or TCPDF.
// For this tutorial/demo, we'll generate a print-friendly HTML page that triggers the browser PDF print.
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Energy Consumption Report - SmartEnergy</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #4f46e5; margin: 0; }
        .user-info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f9fafb; font-weight: bold; }
        .summary { margin-top: 30px; padding: 20px; background: #f3f4f6; border-radius: 8px; }
        .summary-item { font-size: 1.2rem; margin-bottom: 10px; }
        .summary-item strong { color: #4f46e5; }
        .footer { margin-top: 50px; text-align: center; font-size: 0.8rem; color: #666; }
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer; background: #4f46e5; color: white; border: none; border-radius: 4px;">Print / Save as PDF</button>
        <button onclick="window.close()" style="padding: 10px 20px; cursor: pointer; background: #eee; color: #333; border: none; border-radius: 4px; margin-left: 10px;">Close</button>
    </div>

    <div class="header">
        <h1>SmartEnergy Report</h1>
        <p>Detailed Energy Consumption Breakdown</p>
    </div>

    <div class="user-info">
        <p><strong>Username:</strong> <?php echo htmlspecialchars($_SESSION['user_name']); ?></p>
        <p><strong>Report Date:</strong> <?php echo date('F d, Y h:i A'); ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Appliance</th>
                <th>Wattage (W)</th>
                <th>Time (Hrs)</th>
                <th>Consumption (Units)</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($records as $row): ?>
            <tr>
                <td><?php echo date('M d, Y', strtotime($row['date_recorded'])); ?></td>
                <td><?php echo htmlspecialchars($row['appliance_name']); ?></td>
                <td><?php echo $row['wattage']; ?></td>
                <td><?php echo $row['hours_used']; ?></td>
                <td><?php echo number_format($row['consumption_kwh'], 3); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="summary">
        <div class="summary-item">Total Energy Consumed: <strong><?php echo number_format($total_units, 2); ?> Units</strong></div>
        <div class="summary-item">Estimated TANGEDCO Bill: <strong>₹<?php echo number_format($total_cost, 2); ?></strong></div>
        <p><small>* Bill estimation based on current Tamil Nadu residential tariff slabs.</small></p>
    </div>

    <div class="footer">
        Generated by SmartEnergy Management System &copy; <?php echo date('Y'); ?>
    </div>

    <script>
        // Optional: Auto-open print dialog
        // window.onload = function() { window.print(); }
    </script>
</body>
</html>